server:
  port: 8083

spring:
  application:
    name: reviewms

  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: postgres
    password: suvam123

  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
