server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: companyms
          uri: http://localhost:8081
          predicates:
            - Path=/companies/**

        - id: jobms
          uri: http://localhost:8082
          predicates:
            - Path=/jobs/**

        - id: reviewms
          uri: http://localhost:8083
          predicates:
            - Path=/reviews/**

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
