spring:
  application:
    name: jobms

  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: postgres
    password: suvam123

  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true